### ISSUE TITLE
Readme not up to date

### ISSUE THREAD

**Issue by sesas** [DualSpark/cloudformation-environmentbase#1]
I know we are working on it, but I just wanted to note down this issue before I forget and becomes untracked. 

The README makes it seem like you can just pull this repo, do a `pip install -e .` and then run `environmentbase -h` to see the cmd options and even launch a VPC with 1 public subnet and 1 private, with a bastion instance etc. 

But as of this version of the code, that does not happen.  
On `master` I had this error:

```
IOError: [Errno 2] No such file or directory: u'ami_cache.json'
```

and on the `feature-0.4.0` I got:

```
 File "/Users/gabrielreyla/dev/cloudformation-environmentbase/src/environmentbase/environmentbase.py", line 4, in <module>
    import Template
ImportError: No module named Template
```

**Comment by gimballock** [comment]
I retried from the latest code on a fresh virtual environment and everything seems good to go. Can you confirm?

**Comment by sesas** [comment]
Just tested, now it comes up with no error, but the documentation needs to be updated with the `deploy` step and remove the `--config` flag example (as it doesn't work)

**Comment by gimballock** [comment]
Done, 
README updated and --help info updated to better explain --config-file functionality.
